[package]
name        = "zser"
description = "A protobuf-inspired minimalistic serialization format with cryptographic authentication"
version     = "0.0.0"
license     = "MIT"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://www.zcred.org"
repository  = "https://github.com/zcred/zser"
readme      = "README.md"
categories  = ["authentication", "cryptography", "encoding"]
keywords    = ["authentication", "cryptography", "security", "serialization", "merkle"]

[dependencies]
error-chain = "0.10"

[dependencies.byteorder]
version = "0.5"
default-features = false

[dev-dependencies]
data-encoding = "2.0.0-rc.1"
leb128 = "0"
serde_json = "1"

[features]
default = ["std"]
std = []
bench = []
