[package]
name        = "veriform"
description = "Cryptographically verifiable data serialization format inspired by Protocol Buffers"
version     = "0.0.1"
license     = "Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
homepage    = "https://github.com/iqlusioninc/veriform/"
repository  = "https://github.com/iqlusioninc/veriform/tree/develop/rust/"
readme      = "README.md"
edition     = "2018"
categories  = ["authentication", "cryptography", "encoding"]
keywords    = ["hashing", "merkle", "protobufs", "security", "serialization"]

[dependencies]
displaydoc = { version = "0.1", default-features = false }
vint64 = { version = "0.2", path = "vint64" }

[features]
default = ["std"]
alloc = []
std = ["alloc"]
